from __future__ import annotations

from decimal import Decimal
from typing import Any, List, Optional, Tuple

class Address:
    @staticmethod
    def from_string(s: str) -> Address: ...

class Authorization: ...
class Credits:
    def __new__(cls, value: Decimal | float | str) -> Credits: ...
    def micro(self) -> MicroCredits: ...
class Execution:
    def execution_id(self) -> Any: ...
class Fee: ...
class Identifier:
    @staticmethod
    def from_string(s: str) -> Identifier: ...
class Literal:
    @staticmethod
    def from_address(address: Address) -> Literal: ...
    @staticmethod
    def from_u64(value: U64) -> Literal: ...
class Locator:
    def __new__(cls, program_id: ProgramID, resource: Identifier) -> Locator: ...
class MicroCredits:
    def __new__(cls, value: int) -> MicroCredits: ...
    def __int__(self) -> int: ...
class PrivateKey:
    @staticmethod
    def from_string(private_key: str) -> PrivateKey: ...
class Process:
    @staticmethod
    def load() -> Process: ...
    def add_program(self, program: Program) -> None: ...
    def authorize(
        self,
        private_key: PrivateKey,
        program_id: ProgramID,
        function_name: Identifier,
        inputs: List[Value],
    ) -> Authorization: ...
    def authorize_fee_public(
        self,
        private_key: PrivateKey,
        base_fee: MicroCredits,
        deployment_or_execution_id: Any,
        priority_fee: Optional[MicroCredits],
    ) -> Authorization: ...
    def execute(self, authorization: Authorization) -> Tuple[Response, Trace]: ...
    def verify_execution(self, execution: Execution) -> None: ...
    def verify_fee(self, fee: Fee, deployment_or_execution_id: Any) -> None: ...
class Program:
    @staticmethod
    def credits() -> Program: ...
    def id(self) -> ProgramID: ...
class ProgramID: ...
class Query:
    @staticmethod
    def rest(url: str) -> Query: ...
class Response: ...
class Trace:
    def prepare(self, query: Query) -> None: ...
    def prove_execution(self, locator: Locator) -> Execution: ...
    def prove_fee(self) -> Fee: ...
class Transaction:
    @staticmethod
    def from_execution(execution: Execution, fee: Optional[Fee]) -> Transaction: ...
    def to_json(self) -> str: ...
class U64:
    def __new__(cls, value: int) -> U64: ...
class Value:
    @staticmethod
    def from_literal(literal: Literal) -> Value: ...
